### ISSUE TITLE
[52ac2ea][X_scaler.transform] ValueError: operands could not be broadcast together with shapes (1,7968) (1992,) (1,7968)

### ISSUE THREAD

**Issue by chatmoon** [chatmoon/SDC_PRJ05_Vehicle_Detection#1]
**# REF :** 52ac2ea

**# PY FILES :**
. '.\_PRJ05_\module\main_pipeline.py'

**# SCENARIO :**
1. run `main_pipeline.py`

**# EXPECTED RESULT:**
. Generate a video as expected in project05 (cars should be detected successfully)  

**# CURRENT RESULT:**   
```
D:\INSTALL\Anaconda3\envs\keras\python.exe D:/USER/_PROJECT_/_PRJ05_/_1_WIP/_1_forge/_v0_/module/main_pipeline.py
[SHAPE] spatial_features (3072,), hist_features (192,), hog_features (4704,)
[SHAPE] spatial_features (3072,), hist_features (192,), hog_features (4704,)
[SHAPE] spatial_features (3072,), hist_features (192,), hog_features (4704,)
[SHAPE] spatial_features (3072,), hist_features (192,), hog_features (4704,)
[SHAPE] spatial_features (3072,), hist_features (192,), hog_features (4704,)
[SHAPE] spatial_features (3072,), hist_features (192,), hog_features (4704,)
Traceback (most recent call last):
  File "D:/USER/_PROJECT_/_PRJ05_/_1_WIP/_1_forge/_v0_/module/main_pipeline.py", line 81, in <module>
    main()
  File "D:/USER/_PROJECT_/_PRJ05_/_1_WIP/_1_forge/_v0_/module/main_pipeline.py", line 77, in main
    test(args, mp4=0)
  File "D:/USER/_PROJECT_/_PRJ05_/_1_WIP/_1_forge/_v0_/module/main_pipeline.py", line 68, in test
    video(video_input, video_output)
  File "D:/USER/_PROJECT_/_PRJ05_/_1_WIP/_1_forge/_v0_/module/main_pipeline.py", line 61, in video
    video_clip = clip1.fl_image(process_image)
  File "D:\INSTALL\Anaconda3\envs\keras\lib\site-packages\moviepy\video\VideoClip.py", line 506, in fl_image
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "D:\INSTALL\Anaconda3\envs\keras\lib\site-packages\moviepy\Clip.py", line 137, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "<decorator-gen-57>", line 2, in set_make_frame
  File "D:\INSTALL\Anaconda3\envs\keras\lib\site-packages\moviepy\decorators.py", line 14, in outplace
    f(newclip, *a, **k)
  File "D:\INSTALL\Anaconda3\envs\keras\lib\site-packages\moviepy\video\VideoClip.py", line 661, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-10>", line 2, in get_frame
  File "D:\INSTALL\Anaconda3\envs\keras\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "D:\INSTALL\Anaconda3\envs\keras\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "D:\INSTALL\Anaconda3\envs\keras\lib\site-packages\moviepy\Clip.py", line 137, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "D:\INSTALL\Anaconda3\envs\keras\lib\site-packages\moviepy\video\VideoClip.py", line 506, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "D:/USER/_PROJECT_/_PRJ05_/_1_WIP/_1_forge/_v0_/module/main_pipeline.py", line 52, in process_image
    _ , heat_map = find_cars(var, image) # var['scale'])
  File "D:\USER\_PROJECT_\_PRJ05_\_1_WIP\_1_forge\_v0_\module\step06.py", line 78, in find_cars
    test_features    = X_scaler.transform(np.hstack((spatial_features, hist_features, hog_features)).reshape(1, -1))
  File "D:\INSTALL\Anaconda3\envs\keras\lib\site-packages\sklearn\preprocessing\data.py", line 692, in transform
    X -= self.mean_
ValueError: operands could not be broadcast together with shapes (1,7968) (1992,) (1,7968) 
```

**# ENVIRONMENT :**
- platform : win7-64
- GPU: Nvidia Quadro K2100M
 ---
# Name                    Version                   Build  Channel
absl-py                   0.1.10                    <pip>
asn1crypto                0.24.0                   py36_0    conda-forge
astor                     0.6.2                     <pip>
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.5                      py36_0    conda-forge
bleach                    2.1.3                      py_0    conda-forge
bleach                    1.5.0                     <pip>
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
chardet                   3.0.4                     <pip>
chardet                   3.0.4                    py36_0    conda-forge
cloudpickle               0.5.3                      py_0    conda-forge
colorama                  0.3.9                    py36_0    conda-forge
colorama                  0.3.9                     <pip>
cryptography              2.2.1                    py36_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
dask-core                 0.18.0                     py_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
freetype                  2.8.1                    vc14_0  [vc14]  conda-forge
gast                      0.2.0                     <pip>
get                       1.0.3                     <pip>
git                       2.16.1                        0    anaconda
grpcio                    1.10.0                    <pip>
html5lib                  0.9999999                 <pip>
html5lib                  1.0.1                      py_0    conda-forge
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                     vc14_0  [vc14]  conda-forge
idna                      2.7                      py36_0    conda-forge
idna                      2.6                       <pip>
imageio                   2.3.0                    py36_0    conda-forge
imageio                   2.3.0                     <pip>
intel-openmp              2018.0.0             hd92c6cd_8
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.4.0                     <pip>
ipython                   6.4.0                    py36_0    conda-forge
ipython-genutils          0.2.0                     <pip>
ipython_genutils          0.2.0                    py36_0    conda-forge
ipyvolume                 0.4.5                    py36_0    conda-forge
ipywebrtc                 0.3.0                    py36_0    conda-forge
ipywidgets                7.2.1                    py36_1    conda-forge
jedi                      0.12.0                   py36_0    conda-forge
jedi                      0.12.0                    <pip>
jinja2                    2.10                     py36_0    conda-forge
jpeg                      9b                       vc14_2  [vc14]  conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter_client            5.2.3                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
Keras                     2.1.4                     <pip>
libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
libsodium                 1.0.16                   vc14_0  [vc14]  conda-forge
libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
Markdown                  2.6.11                    <pip>
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.1.2                    py36_0    conda-forge
mistune                   0.8.3                    py36_1    conda-forge
mkl                       2018.0.1             h2108138_4
moviepy                   0.2.3.4                   <pip>
msys2-conda-epoch         20160418                      1
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
networkx                  2.1                      py36_0    conda-forge
notebook                  5.5.0                    py36_0    conda-forge
numpy                     1.14.1                    <pip>
numpy                     1.14.1           py36h4a99626_1
olefile                   0.45.1                   py36_0    conda-forge
opencv                    3.3.1            py36h20b85fd_1
openssl                   1.0.2o                   vc14_0  [vc14]  conda-forge
pandas                    0.22.0           py36h6538335_0
pandoc                    2.2.1                hde52d81_0    conda-forge
pandocfilters             1.4.2                    py36_0    conda-forge
parso                     0.2.1                     <pip>
parso                     0.2.1                      py_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pickleshare               0.7.4                     <pip>
Pillow                    5.1.0                     <pip>
pillow                    5.1.0                    py36_0    conda-forge
pip                       10.0.1                    <pip>
pip                       9.0.1                    py36_5
post                      1.0.2                     <pip>
prompt-toolkit            1.0.15                    <pip>
prompt_toolkit            1.0.15                   py36_0    conda-forge
protobuf                  3.5.1                     <pip>
public                    1.0.3                     <pip>
pycparser                 2.18                     py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
Pygments                  2.2.0                     <pip>
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
python                    3.6.4                h6538335_1
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2018.3                     py_0    conda-forge
pywavelets                0.5.2                    py36_1    conda-forge
pywinpty                  0.5.4                    py36_0    conda-forge
PyYAML                    3.12                      <pip>
pyzmq                     17.0.0                   py36_4    conda-forge
pyzmq                     17.0.0                    <pip>
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
query-string              1.0.2                     <pip>
request                   1.0.2                     <pip>
requests                  2.18.4                    <pip>
requests                  2.19.1                   py36_0    conda-forge
scikit-image              0.14.0           py36h6538335_1    conda-forge
scikit-learn              0.19.1           py36h53aea1b_0
scipy                     1.0.0                     <pip>
scipy                     1.0.0            py36h1260518_0
send2trash                1.5.0                      py_0    conda-forge
setuptools                38.5.1                    <pip>
setuptools                38.5.1                   py36_0
simplegeneric             0.8.1                     <pip>
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                    <pip>
six                       1.11.0                   py36_1    conda-forge
tensorboard               1.6.0                     <pip>
tensorflow                1.6.0                     <pip>
termcolor                 1.1.0                     <pip>
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.6.7                    vc14_0  [vc14]  conda-forge
toolz                     0.9.0                      py_0    conda-forge
tornado                   4.5.3                    py36_0    conda-forge
tqdm                      4.23.3                    <pip>
traitlets                 4.3.2                    py36_0    conda-forge
traittypes                0.2.1                    py36_0    conda-forge
urllib3                   1.22                      <pip>
urllib3                   1.23                     py36_0    conda-forge
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wcwidth                   0.1.7                    py36_0    conda-forge
wcwidth                   0.1.7                     <pip>
webencodings              0.5.1                    py36_0    conda-forge
Werkzeug                  0.14.1                    <pip>
wheel                     0.30.0           py36h6c3ec14_1
wheel                     0.30.0                    <pip>
widgetsnbextension        3.2.1                    py36_0    conda-forge
win_inet_pton             1.0.1                    py36_1    conda-forge
wincertstore              0.2              py36h7fe50ca_0
winpty                    0.4.3                         4    conda-forge
zeromq                    4.2.5                    vc14_1  [vc14]  conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

**Comment by chatmoon** [comment]
**# MENTOR :** Nandan 

### 1. Shapes not maching
Looks like the three feature sets (spatial,hist and hog) are not matching in their sizes. You have different sizes. That is (1,7968) (1992,) (1,7968).

Check your individual feature(spatial, hist and hog) output and how you are getting those unmatching sizes. Specifically hist.

### 2. Code missing
`If hog_channel == 'ALL'` is missing. 
change step05.py code as per the above answer: [ [image ](https://raw.githubusercontent.com/chatmoon/SDC_PRJ05_Vehicle_Detection/master/_1_wip/examples/mentor_180712-0834.jpg)]

let me know if it helped
Image

P.S. above image is the screenshot of the discussion forum answer. Kindly try as suggested above and let me know if it worked :) [ [forum](https://discussions.udacity.com/t/valueerror-operands-could-not-be-broadcast-together-with-shapes-1-6108-3168-1-6108/454181/10) ]

**Comment by chatmoon** [comment]
I've tried to track back the issue.
I've found out that the problem is about the shape of feature(spatial, hist and hog).

The program runs well for the first 6 frames: 
```
[SHAPE] spatial_features (3072,), hist_features (192,), hog_features (4704,) 
[SHAPE] spatial_features (3072,), hist_features (192,), hog_features (4704,) 
[SHAPE] spatial_features (3072,), hist_features (192,), hog_features (4704,) 
[SHAPE] spatial_features (3072,), hist_features (192,), hog_features (4704,) 
[SHAPE] spatial_features (3072,), hist_features (192,), hog_features (4704,) 
[SHAPE] spatial_features (3072,), hist_features (192,), hog_features (4704,)
```

And then crashs due to a shape and broadcasting issue.

Even thought, I've implemented the `if hog_channel='ALL'`, the program still crashes.
Same result with `hist_features = color_hist(feature_image, nbins=hist_bins)`.

I am reading all the threads that I can find in the forum.

In my opinion, the problem comes from spatial_features and hog_features.
I had a look on` bin_spatial()` and `get_hog_features()` functions.

It seems the problem might be located in `step02.py`.
I will let you know if it is fixed
